task 0

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,22 +1,28 @@
 #!/usr/bin/env bash
-# Transfer file to server using scp
+# copy to server using scp
 
-if [ $# -lt 4 ]; then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
+if [ $# -lt 4 ]
+then
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
 fi
+
+#Initializing variables
 
 path_to_file=$1
 ip=$2
 username=$3
-path_to_ssh_key=$4
+path_to_ssh_key=$4 
 
-# Transfer file using scp with strict host key checking disabled
+#disable strict key check
+
 scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
-if [ $? -eq 0 ]; then
-    echo "File transfer successful"
-else
-    echo "Transfer failed"
-fi
+#transfer status
 
+if [ $? -eq 0 ]
+then
+	echo "FILE TRANSFER SUCCESSFUL"
+else
+	echo "TRANFER FAILED"
+fi
